<?php
namespace Kernel;
use App\Console\Commands\testArt;
use Illuminate\Contracts\Http\Kernel as HttpKernel;
use Illuminate\Foundation\Configuration\ApplicationBuilder;
use Illuminate\Foundation\Configuration\Middleware;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as AppRouteServiceProvider;
use Illuminate\Foundation\Configuration\Exceptions as ConfigurationException;
use Exception as BaseException;
use Illuminate\Http\Request;

class Configuration extends ApplicationBuilder {
    public function handleRouting()
    {
        parent::withRouting(
            web: $this->app->basePath("app/routes.php"));
        return $this;
    }

    public function handleMiddleware()
    {
        parent::withMiddleware(function (Middleware $middleware) {
            //
        });
        return $this;
    }

    public function handleExceptions()
    {
        parent::withExceptions(function (ConfigurationException $exceptions) {
            $exceptions->render(function (BaseException $e, Request $request) {
                return response()->json([
                    'message' => $e->getMessage()
                ], 200);
            });
        }); // TODO: Change the autogenerated stub
        return $this;

    }

    public function create()
    {
        $this->app->useBootstrapPath(storage_path("bootstrap"));
        $this->handleRouting()->handleMiddleware()->handleExceptions();
        $this->withCommands([
            testArt::class
        ]);
        return $this->app;
    }

}